/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as RWorkflowIdRunIdRouteImport } from './routes/r/$workflowId.$runId'
import { Route as AuthenticatedDashboardCampaignsIndexRouteImport } from './routes/_authenticated/dashboard/campaigns/index'
import { Route as AuthenticatedDashboardCallsIndexRouteImport } from './routes/_authenticated/dashboard/calls/index'
import { Route as AuthenticatedDashboardAgentsIndexRouteImport } from './routes/_authenticated/dashboard/agents/index'
import { Route as AuthenticatedDashboardCampaignsCreateRouteImport } from './routes/_authenticated/dashboard/campaigns/create'
import { Route as AuthenticatedDashboardCampaignsIdRouteImport } from './routes/_authenticated/dashboard/campaigns/$id'
import { Route as AuthenticatedDashboardCallsRunIdRouteImport } from './routes/_authenticated/dashboard/calls/$runId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const RWorkflowIdRunIdRoute = RWorkflowIdRunIdRouteImport.update({
  id: '/r/$workflowId/$runId',
  path: '/r/$workflowId/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardCampaignsIndexRoute =
  AuthenticatedDashboardCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCallsIndexRoute =
  AuthenticatedDashboardCallsIndexRouteImport.update({
    id: '/calls/',
    path: '/calls/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAgentsIndexRoute =
  AuthenticatedDashboardAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCampaignsCreateRoute =
  AuthenticatedDashboardCampaignsCreateRouteImport.update({
    id: '/campaigns/create',
    path: '/campaigns/create',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCampaignsIdRoute =
  AuthenticatedDashboardCampaignsIdRouteImport.update({
    id: '/campaigns/$id',
    path: '/campaigns/$id',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCallsRunIdRoute =
  AuthenticatedDashboardCallsRunIdRouteImport.update({
    id: '/calls/$runId',
    path: '/calls/$runId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/r/$workflowId/$runId': typeof RWorkflowIdRunIdRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/calls/$runId': typeof AuthenticatedDashboardCallsRunIdRoute
  '/dashboard/campaigns/$id': typeof AuthenticatedDashboardCampaignsIdRoute
  '/dashboard/campaigns/create': typeof AuthenticatedDashboardCampaignsCreateRoute
  '/dashboard/agents/': typeof AuthenticatedDashboardAgentsIndexRoute
  '/dashboard/calls/': typeof AuthenticatedDashboardCallsIndexRoute
  '/dashboard/campaigns/': typeof AuthenticatedDashboardCampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/r/$workflowId/$runId': typeof RWorkflowIdRunIdRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/calls/$runId': typeof AuthenticatedDashboardCallsRunIdRoute
  '/dashboard/campaigns/$id': typeof AuthenticatedDashboardCampaignsIdRoute
  '/dashboard/campaigns/create': typeof AuthenticatedDashboardCampaignsCreateRoute
  '/dashboard/agents': typeof AuthenticatedDashboardAgentsIndexRoute
  '/dashboard/calls': typeof AuthenticatedDashboardCallsIndexRoute
  '/dashboard/campaigns': typeof AuthenticatedDashboardCampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/r/$workflowId/$runId': typeof RWorkflowIdRunIdRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/calls/$runId': typeof AuthenticatedDashboardCallsRunIdRoute
  '/_authenticated/dashboard/campaigns/$id': typeof AuthenticatedDashboardCampaignsIdRoute
  '/_authenticated/dashboard/campaigns/create': typeof AuthenticatedDashboardCampaignsCreateRoute
  '/_authenticated/dashboard/agents/': typeof AuthenticatedDashboardAgentsIndexRoute
  '/_authenticated/dashboard/calls/': typeof AuthenticatedDashboardCallsIndexRoute
  '/_authenticated/dashboard/campaigns/': typeof AuthenticatedDashboardCampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/r/$workflowId/$runId'
    | '/dashboard/'
    | '/dashboard/calls/$runId'
    | '/dashboard/campaigns/$id'
    | '/dashboard/campaigns/create'
    | '/dashboard/agents/'
    | '/dashboard/calls/'
    | '/dashboard/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/r/$workflowId/$runId'
    | '/dashboard'
    | '/dashboard/calls/$runId'
    | '/dashboard/campaigns/$id'
    | '/dashboard/campaigns/create'
    | '/dashboard/agents'
    | '/dashboard/calls'
    | '/dashboard/campaigns'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/r/$workflowId/$runId'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/calls/$runId'
    | '/_authenticated/dashboard/campaigns/$id'
    | '/_authenticated/dashboard/campaigns/create'
    | '/_authenticated/dashboard/agents/'
    | '/_authenticated/dashboard/calls/'
    | '/_authenticated/dashboard/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RWorkflowIdRunIdRoute: typeof RWorkflowIdRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/r/$workflowId/$runId': {
      id: '/r/$workflowId/$runId'
      path: '/r/$workflowId/$runId'
      fullPath: '/r/$workflowId/$runId'
      preLoaderRoute: typeof RWorkflowIdRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/campaigns/': {
      id: '/_authenticated/dashboard/campaigns/'
      path: '/campaigns'
      fullPath: '/dashboard/campaigns/'
      preLoaderRoute: typeof AuthenticatedDashboardCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/calls/': {
      id: '/_authenticated/dashboard/calls/'
      path: '/calls'
      fullPath: '/dashboard/calls/'
      preLoaderRoute: typeof AuthenticatedDashboardCallsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/agents/': {
      id: '/_authenticated/dashboard/agents/'
      path: '/agents'
      fullPath: '/dashboard/agents/'
      preLoaderRoute: typeof AuthenticatedDashboardAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/campaigns/create': {
      id: '/_authenticated/dashboard/campaigns/create'
      path: '/campaigns/create'
      fullPath: '/dashboard/campaigns/create'
      preLoaderRoute: typeof AuthenticatedDashboardCampaignsCreateRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/campaigns/$id': {
      id: '/_authenticated/dashboard/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/dashboard/campaigns/$id'
      preLoaderRoute: typeof AuthenticatedDashboardCampaignsIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/calls/$runId': {
      id: '/_authenticated/dashboard/calls/$runId'
      path: '/calls/$runId'
      fullPath: '/dashboard/calls/$runId'
      preLoaderRoute: typeof AuthenticatedDashboardCallsRunIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardCallsRunIdRoute: typeof AuthenticatedDashboardCallsRunIdRoute
  AuthenticatedDashboardCampaignsIdRoute: typeof AuthenticatedDashboardCampaignsIdRoute
  AuthenticatedDashboardCampaignsCreateRoute: typeof AuthenticatedDashboardCampaignsCreateRoute
  AuthenticatedDashboardAgentsIndexRoute: typeof AuthenticatedDashboardAgentsIndexRoute
  AuthenticatedDashboardCallsIndexRoute: typeof AuthenticatedDashboardCallsIndexRoute
  AuthenticatedDashboardCampaignsIndexRoute: typeof AuthenticatedDashboardCampaignsIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardCallsRunIdRoute:
      AuthenticatedDashboardCallsRunIdRoute,
    AuthenticatedDashboardCampaignsIdRoute:
      AuthenticatedDashboardCampaignsIdRoute,
    AuthenticatedDashboardCampaignsCreateRoute:
      AuthenticatedDashboardCampaignsCreateRoute,
    AuthenticatedDashboardAgentsIndexRoute:
      AuthenticatedDashboardAgentsIndexRoute,
    AuthenticatedDashboardCallsIndexRoute:
      AuthenticatedDashboardCallsIndexRoute,
    AuthenticatedDashboardCampaignsIndexRoute:
      AuthenticatedDashboardCampaignsIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RWorkflowIdRunIdRoute: RWorkflowIdRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
